;;;; package.lisp
(defpackage #:april-gpu/utils
  (:use #:cl #:vk)
  (:export
   #:*api-version*
   #:*vk-validation-layer-name*
   #:*fence-timeout*
   #:with-allocated-memory
   #:with-mapped-memory
   #:copy-to-device
   #:make-default-application-info
   #:make-default-debug-utils-messenger-create-info
   #:make-default-render-pass-begin-info
   #:make-default-queue-create-infos
   #:with-instance
   #:with-device
   #:with-surface
   #:with-swapchain
   #:with-depth-buffer
   #:with-render-pass
   #:with-shader-module
   #:with-compiled-shader-module
   #:with-framebuffers
   #:with-command-pool
   #:with-command-buffer
   #:record-command-buffer
   #:with-semaphore
   #:with-fence
   #:with-gfx-base
   #:with-gfx
   #:with-uniform-buffer
   #:with-vertex-buffer
   #:with-simple-descriptor-set-layout
   #:with-simple-descriptor-pool
   #:with-simple-descriptor-set
   #:with-simple-pipeline-layout
   #:with-simple-graphics-pipeline
   #:find-type-index
   #:find-graphics-queue-family-index
   #:find-graphics-and-present-queue-family-indices
   #:determine-swapchain-extent
   #:pick-color-format
   #:pick-depth-format
   #:create-render-pass
   #:define-debug-utils-messenger-callback
   #:default-debug-utils-log-callback
   #:create-graphics-pipeline
   #:update-descriptor-sets
   #:swapchain-data
   #:color-format
   #:images
   #:swapchain
   #:image-views
   #:image-data
   #:img-format
   #:image
   #:device-memory
   #:image-view
   #:buffer-data
   #:buffer
   #:device-memory
   #:texture-data
   #:tex-format
   #:extent
   #:needs-staging-p
   #:staging-buffer-data
   #:sampler
   #:clear-handle-data
   #:make-swapchain-data
   #:allocated-device-memory
   #:make-framebuffers
   #:make-image-data
   #:make-depth-buffer-data
   #:make-buffer-data
   #:make-texture-data
   #:set-image-layout
   #:set-texture-image
   #:push-flag
   #:one-time-submit
   #:copy-to-buffer
   #:checkerboard-image-generator))

(defpackage #:april-gpu
  (:use #:cl #:iterate #:access #:april-gpu/utils))
